name: Track Cursor Version Downloads

on:
  schedule:
    # 每一小时运行一次
    - cron: '0 * * * *'
  # 也允许手动触发
  workflow_dispatch:

jobs:
  get-latest-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tracker script
        run: npm run update

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(downloads): update Cursor version download links [bot]" && git push)
